---
name: Main

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - main
      - master

permissions: read-all

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  main-job:
    name: Main job name
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone other-branch
        run: |
          git clone https://github.com/L3odr0id/test-commit-to-other-branch.git --branch other-branch --single-branch other-branch-path

      - name: Create file
        run: |
          mkdir -p other-branch-path/src/lib/data/
          touch other-branch-path/src/lib/data/experimental.txt
          date +"%Y-%m-%d %H:%M:%S" > other-branch-path/src/lib/data/experimental.txt
          echo "Created file with date and time"
      
      - name: Bot Details
        id: bot-details
        uses: raven-actions/bot-details@v1
      
      - name: Commit & push
        run: |
          cd other-branch-path
          git config --global user.name "${{ steps.bot-details.outputs.name }}"
          git config --global user.email "${{ steps.bot-details.outputs.email }}"
          git add src/lib/data/experimental.txt
          git commit -m "[ bot ] Update runs statistics"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push origin other-branch

      # - name: Push to other-branch
      #   uses: stefanzweifel/git-auto-commit-action@v7
      #   with:
      #     commit_message: >
      #       [ bot ] Update runs statistics
      #     commit_user_name: ${{ steps.bot-details.outputs.name }}
      #     commit_user_email: ${{ steps.bot-details.outputs.email }}
      #     commit_author: ${{ steps.bot-details.outputs.name-email }}
      #     branch: other-branch
      #     repository: other-branch-path
      #     token: ${{ secrets.GITHUB_TOKEN }}
