---
name: Main

on:
  push:
    branches:
      - main
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - main
      - master

permissions: read-all

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  main-job:
    name: Main job name
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |

      - name: Push to other-branch
        run: |