name: Other

on:
  push:
    branches:
      - other-branch

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  other-job:
    name: Read and print file content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other-branch
        uses: actions/checkout@v4

      - name: Read file content
        run: |
          echo "File content of src/lib/data/experimental.txt:"
          cat src/lib/data/experimental.txt
